//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRestriction
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> RestrictionId { get; set; }
    
        public virtual Restriction Restriction { get; set; }
        public virtual User User { get; set; }
    }
}
